# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-24 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=255)),
                ('g_email', models.CharField(max_length=30)),
                ('g_password', models.CharField(max_length=30)),
                ('g_contact', models.CharField(max_length=255)),
                ('g_description', models.TextField(max_length=255)),
                ('g_aboutme', models.CharField(max_length=255)),
                ('g_created_at', models.DateTimeField(auto_now_add=True)),
                ('g_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=255)),
                ('t_email', models.CharField(max_length=30)),
                ('t_password', models.CharField(max_length=30)),
                ('t_contact', models.CharField(max_length=255)),
                ('t_created_at', models.DateTimeField(auto_now_add=True)),
                ('t_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
